//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshopAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public LoginUser()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string pass { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
