//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshopAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.OrderLines = new HashSet<OrderLine>();
            this.Products = new HashSet<Product>();
            this.ShoppingOrders = new HashSet<ShoppingOrder>();
        }
    
        public int id { get; set; }
        public Nullable<int> UserProfile { get; set; }
    
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual ICollection<ShoppingOrder> ShoppingOrders { get; set; }
    }
}
